#!/bin/sh

pushd .
cd source

# clean pjsip folder
echo ""
echo In directory: `pwd`
git clean -xdn
echo "CTRL+C to cancel or press any key to continue."
read
git clean -xdf

# configure PJSIP builds
cp ../config_site.h pjlib/include/pj/config_site.h
cat pjlib/include/pj/config_site.h

export ARCH="-arch armv7"

# copy G729 stuff into places
cp -iv ../g729/g729a_include/*.h third_party/
cp ../g729/pj_g729.h third_party/
cp ../g729/pj_g729.c pjmedia/src/pjmedia-codec/g729.c # so it compiles as part of pjsip

mkdir -p third_party/lib
cp ../g729/libg729a.a third_party/lib/libg729codec-arm-apple-darwin9.a

# ... and build
./configure-iphone | tee ../configure.log
make depA | tee ../make-dep.log
make | tee ../make.log
popd

# copy all built static libs into one folder so it's easy to use.
for x in `find source | grep "\.a$"`
do
  cp ./$x ./lib
done

# list all include folders for convenience (when configuring the xcode target)
echo
echo "### includes"
find source | grep "\\include$"

