#!/bin/sh

pushd .
cd source

# clean pjsip folder
echo ""
echo In directory: `pwd`
git clean -xdn
echo "CTRL+C to cancel or press any key to continue."
read
git clean -xdf

# configure PJSIP builds
cp ../config_site.h pjlib/include/pj/config_site.h
cat pjlib/include/pj/config_site.h

export ARCH="-arch armv7"

# copy libg729a.a into pjsib lib search path
mkdir -p third_party/g729/lib
cp ../g729/libg729a.a third_party/g729/lib

# ... and build
./configure-iphone --enable-g729-codec | tee ../configure.log
make depA | tee ../make-dep.log
make | tee ../make.log
popd

# copy all built static libs into one folder so it's easy to use.
for x in `find source | grep "\.a$"`
do
  cp ./$x ./lib
done

# list all include folders for convenience (when configuring the xcode target)
echo
echo "### includes"
find source | grep "\\include$"

