#!/bin/sh

# An experimental script to recursively copy all folders that has 'include' folder in it, into 'headers' folder.
# This is to save disk space rather than having to include a ~70MB source folder (after compiled).
# It doesn't work right now. Seems like files other than in the 'include' folder is needed.

for x in `find source | grep "\\include$"`
do
  # remove /include from our destination path
  # example: newDst=$(echo "abcabc" | sed 's/a/x/g')
  destinationPath=$(echo $x | sed 's/\/include//g')
  destinationPath="./headers/$destinationPath"
  #echo "dst:" $x $destinationPath

  echo ">> copying" $x "to" $destinationPath
  mkdir -p $destinationPath
  cp -r ./$x $destinationPath
done