#!/bin/sh

# List all include folders and related arch for configuring Xcode

echo
echo "### includes"
find source | grep "\\include$" | sort

echo
echo "### arch"
find source | grep "\.a$" | \
  xargs lipo -info 2>/dev/null | grep "rchitecture" | \
  sed -El "s/^.+\: .+\/(.+) (are|is architecture)\: (.+)$/\\3 - \\1/g" | \
  sort

