var files =
[
    [ "Gossip.h", "_gossip_8h_source.html", null ],
    [ "GSAccount.h", "_g_s_account_8h_source.html", null ],
    [ "GSAccount.m", "_g_s_account_8m_source.html", null ],
    [ "GSAccountConfiguration.h", "_g_s_account_configuration_8h_source.html", null ],
    [ "GSAccountConfiguration.m", "_g_s_account_configuration_8m_source.html", null ],
    [ "GSCall.h", "_g_s_call_8h_source.html", null ],
    [ "GSCall.m", "_g_s_call_8m_source.html", null ],
    [ "GSCodecInfo.h", "_g_s_codec_info_8h_source.html", null ],
    [ "GSCodecInfo.m", "_g_s_codec_info_8m_source.html", null ],
    [ "GSConfiguration.h", "_g_s_configuration_8h_source.html", null ],
    [ "GSConfiguration.m", "_g_s_configuration_8m_source.html", null ],
    [ "GSDispatch.h", "_g_s_dispatch_8h_source.html", null ],
    [ "GSDispatch.m", "_g_s_dispatch_8m_source.html", null ],
    [ "GSIncomingCall.h", "_g_s_incoming_call_8h_source.html", null ],
    [ "GSIncomingCall.m", "_g_s_incoming_call_8m_source.html", null ],
    [ "GSNotifications.h", "_g_s_notifications_8h_source.html", null ],
    [ "GSNotifications.m", "_g_s_notifications_8m_source.html", null ],
    [ "GSOutgoingCall.h", "_g_s_outgoing_call_8h_source.html", null ],
    [ "GSOutgoingCall.m", "_g_s_outgoing_call_8m_source.html", null ],
    [ "GSPJUtil.h", "_g_s_p_j_util_8h_source.html", null ],
    [ "GSPJUtil.m", "_g_s_p_j_util_8m_source.html", null ],
    [ "GSUserAgent.h", "_g_s_user_agent_8h_source.html", null ],
    [ "GSUserAgent.m", "_g_s_user_agent_8m_source.html", null ],
    [ "PJSIP.h", "_p_j_s_i_p_8h_source.html", null ],
    [ "Util.h", "_util_8h_source.html", null ]
];